GET http://[::1]:8084/jsonapi HTTP/1.1

###

GET http://[::1]:8084/jsonapi/node/article?page[limit]=1

###

GET http://[::1]:8084/router/translate-path?path=/courses/html
Content-Type:: application/json
Authorization: {{access_token}}

###

GET http://[::1]:8084/router/translate-path?path=/html/introduction-html

###

GET http://[::1]:8084/jsonapi/node/lesson
Content-Type:: application/json
Authorization: {{access_token}}
###

GET http://[::1]:8084/jsonapi/node/lesson/7e89aa0d-073e-4de1-80f6-7d609631ebbc

###

GET http://[::1]:8084/jsonapi/node/lesson/7e89aa0d-073e-4de1-80f6-7d609631ebbc?include=field_paragraph_lesson.field_image
###


GET http://[::1]:8084/jsonapi/node/lesson/7e89aa0d-073e-4de1-80f6-7d609631ebbc/field_paragraph_body_content

###


GET http://[::1]:8084/jsonapi/paragraph/paragraph_image/

###

GET http://[::1]:8084/jsonapi/paragraph/paragraph_image/2b2484e6-352d-4bbc-bede-fb8e5340ee5c

###

GET http://[::1]:8084/jsonapi/node/completed_lessons

###

GET http://[::1]:8084/jsonapi/node/lesson?filter[field_subject_of_lesson.meta.drupal_internal__target_id]=7

###
GET http://[::1]:8084/jsonapi/api/v1/html?_format=json

###
GET http://[::1]:8084/jsonapi/taxonomy_term/subject

###
GET http://[::1]:8084/jsonapi/taxonomy_term/subject/f3282593-c751-482e-82a2-0c05e1356871

###
GET http://[::1]:8084/router/translate-path?path=/html

###
POST http://[::1]:8084/user/register?_format=json HTTP/1.1
Content-Type: application/json
Authorization: Basic testuser1:loremipsum1!

{
    "name": {"value": {{test_username}}},
    "mail": {"value":{{test_email}}}
}
### mailsystem + smtp

### rest_register_verify_email 1 
POST http://[::1]:8084/rest/create-account?_format=json HTTP/1.1
Content-Type: application/json

{
    "mail": {{test_username}},
    "pass": {{test_password}}
}

### rest_register_verify_email 2 
POST http://[::1]:8084/rest/verify-account?_format=json HTTP/1.1
Content-Type: application/json

{
  "name": {{test_username}},
  "temp_token": {{temp_token}}
}


###
POST http://[::1]:8084/rest/verify-account?_format=json HTTP/1.1
Content-Type: application/json  

{
  "name": "your@yoursite.email",
  "temp_token":"TOKEN_SENT_IN_EMAIL"
}


### need https://www.debugbear.com/basic-auth-header-generator
GET http://[::1]:8084/node/1
Content-Type:: application/json
Authorization: Basic {{username}}:{{password}}

###
GET http://[::1]:8084/node/1
Content-Type:: application/json
Authorization: Basic am1hcmlhbm86bEkzM3kjJiNVN2hjSFNTTg==

### 
GET http://[::1]:8084/user/login?_format=json
Content-Type:: application/json
Authorization: Basic {{username}}:{{password}}

###
GET http://[::1]:8084/session/token

###
### Oauth Get Bearer Token - simple_oauth + simple_oauth_password_grant
POST http://[::1]:8084/oauth/token HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="grant_type"
client_credentials

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="client_id"
{{client_id}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="client_secret"
{{client_secret}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="scope"
student

------WebKitFormBoundary7MA4YWxkTrZu0gW--

### How user will Login in Decoupled toget access_token
//POST http://localhost:8084/oauth/token HTTP/1.1
POST /oauth/token HTTP/1.1
Host: localhost:8084
Content-Length: 609
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="grant_type"
password

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="client_id"
{{client_id}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="client_secret"
{{client_secret}}


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"
{{username}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"
{{password}}
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Authorization code grant 
    #Step 1:  POST https://http://[::1]:8084/oauth/authorize?response_type=code&client_id={{client_id}}&scope=student
    #Step 2: https://www.webupps.com/?code={{code}}

  POST http://[::1]:8084/oauth/token HTTP/1.1
  Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

  ------WebKitFormBoundary7MA4YWxkTrZu0gW
  Content-Disposition: form-data; name="client_id"
  {{client_id}}

  ------WebKitFormBoundary7MA4YWxkTrZu0gW
  Content-Disposition: form-data; name="client_secret"
  {{client_secret}}

  ------WebKitFormBoundary7MA4YWxkTrZu0gW
  Content-Disposition: form-data; name="grant_type"
  authorization_code

  ------WebKitFormBoundary7MA4YWxkTrZu0gW
  Content-Disposition: form-data; name="code"
  {{code}}
  ------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Open ID - simple_oauth + simple_oauth_companion + /sites/default/services.yml
GET http://[::1]:8084/oauth/userinfo HTTP/1.1
Content-Type:: application/json
Authorization: {{access_token}}

### Exchange Refresh Token with Access Token
POST  http://[::1]:8084/oauth/token HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="client_id"
{{client_id}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="client_secret"
{{client_secret}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="grant_type"
refresh_token

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="refresh_token"

{{refresh_token}}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

GET http://[::1]:8084/oauth/debug?_format=json HTTP/1.1
Authorization: Bearer {{access_token}}

### Contains RSA Public Key
GET http://[::1]:8084/oauth/jwks HTTP/1.1
Authorization: Bearer {{access_token}}

###

POST http://localhost:8084/user/login?_format=json HTTP/1.1
Content-Type: application/json
X-CSRF-Token: {{XCSRFToken}}

{
    "name": {{username}},
    "pass": {{password}}
}
###

GET http://localhost:8084/user/1?_format=json HTTP/1.1
Content-Type:: application/json
Cookie: {{Cookie}}


###
GET http://[::1]:8084/api/v1/lesson/1?_format=json
Content-Type:: application/json
Authorization: {{access_token}}


###
GET http://[::1]:8084/api/v1/subject/completed/3/1?_format=json
Content-Type:: application/json
Authorization: {{access_token}}

###
GET http://[::1]:8084/api/v1/lesson/completed/1/1?_format=json



### rest_password Step 1: Get Temporary password from Email
POST http://[::1]:8084/user/lost-password?_format=json HTTP/1.1
Content-Type: application/json

{
  "mail": {{username}}
}
### rest_password Step 2: Reset your password with temp password
POST http://[::1]:8084/user/lost-password-reset?_format=json HTTP/1.1
Content-Type: application/json

{
  "name": {{username}},
  "temp_pass":"yvL_80d2UcHprw",
  "new_pass":{{newpassword}}
}
###
POST http://[::1]:8084/admin/content/simple_oauth/oauth2_token/3/delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}
###
POST http://[::1]:8084/oauth/revoke HTTP/1.1
Content-Type: application/json
Authorization: {{access_token}}
###
GET http://[::1]:8084/oauth/debug?_format=json HTTP/1.1
Host: dev-webuppsschool.pantheonsite.io
Authorization: Bearer {{access_token}}


edgar@ealcantara.me

curl --request POST \
  --url https://dev-webuppsschool.pantheonsite.io/oauth2/token/revoke \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data 'token={{access_token}}&token_type_hint=access_token'

curl -X POST \
  -d "token={{access_token}} \
  -d "token_type_hint=access_token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  https://dev-webuppsschool.pantheonsite.io/oauth2/revoke
  
  curl --request POST \
  --url https://dev-webuppsschool.pantheonsite.io/oauth2/token/revoke \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data 'token={{access_token}}&token_type_hint=access_token'


  