GET http://[::1]:8084/jsonapi HTTP/1.1

###

GET http://[::1]:8084/jsonapi/node/article?page[limit]=1

###

GET http://[::1]:8084/router/translate-path?path=/html


###

GET http://[::1]:8084/router/translate-path?path=/html/introduction-html

###

GET http://[::1]:8084/jsonapi/node/lesson
Content-Type:: application/json
Authorization: {{access_token}}
###

GET http://[::1]:8084/jsonapi/node/lesson/7e89aa0d-073e-4de1-80f6-7d609631ebbc

###

GET http://[::1]:8084/jsonapi/node/lesson/7e89aa0d-073e-4de1-80f6-7d609631ebbc?include=field_paragraph_lesson.field_image
###


GET http://[::1]:8084/jsonapi/node/lesson/7e89aa0d-073e-4de1-80f6-7d609631ebbc/field_paragraph_body_content

###


GET http://[::1]:8084/jsonapi/paragraph/paragraph_image/

###

GET http://[::1]:8084/jsonapi/paragraph/paragraph_image/2b2484e6-352d-4bbc-bede-fb8e5340ee5c

###

GET http://[::1]:8084/jsonapi/node/completed_lessons

###

GET http://[::1]:8084/jsonapi/node/lesson?filter[field_subject_of_lesson.meta.drupal_internal__target_id]=7

###
GET http://[::1]:8084/jsonapi/api/v1/html?_format=json

###
GET http://[::1]:8084/jsonapi/taxonomy_term/subject

###
GET http://[::1]:8084/jsonapi/taxonomy_term/subject/f3282593-c751-482e-82a2-0c05e1356871

###
GET http://[::1]:8084/router/translate-path?path=/html

###
POST http://[::1]:8084/user/register?_format=json HTTP/1.1
Content-Type: application/json
Authorization: Basic testuser1:loremipsum1!

{
    "name": {"value": {{test_username}}},
    "mail": {"value":{{test_email}}}
}

###
POST http://[::1]:8084/rest/create-account?_format=json HTTP/1.1
Content-Type: application/json

{
    "mail": {{test_username}},
    "pass": {{test_password}}
}

###
POST http://[::1]:8084/rest/verify-account?_format=json HTTP/1.1
Content-Type: application/json

{
  "name": {{test_username}},
  "temp_token": {{temp_token}}
}


###
POST http://[::1]:8084/rest/verify-account?_format=json HTTP/1.1
Content-Type: application/json  

{
  "name": "your@yoursite.email",
  "temp_token":"TOKEN_SENT_IN_EMAIL"
}


###
GET http://[::1]:8084/node/1
Content-Type:: application/json
Authorization: Basic {{username}}:{{password}}

###
GET http://[::1]:8084/user/login?_format=json
Content-Type:: application/json
Authorization: Basic {{username}}:{{password}}

###
GET http://[::1]:8084/session/token

###
### Oauth Get Bearer Token
POST http://[::1]:8084/oauth/token HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="grant_type"

client_credentials
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="client_id"

{{oauthuser_secretkey}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="client_secret"

{{oauthuser_secretkey}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="scope"

student
------WebKitFormBoundary7MA4YWxkTrZu0gW--
### How user will Login in Decoupled
POST http://[::1]:8084/oauth/token HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="grant_type"

password
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="client_id"

MHLMS3UbrMwh4Okve0LIK3qaZ_0OruMW6J94IM8mx4Q
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

oauthuser
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

jwrOGdtEz%82Svx!6w
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="client_secret"

MC##xaS8B3*eibG$6P
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="scope"

student
------WebKitFormBoundary7MA4YWxkTrZu0gW--

#Open ID gets userinfo part of simple_oauth module  call this module after login
GET http://[::1]:8084/oauth/userinfo HTTP/1.1
Content-Type:: application/json
Authorization: {{access_token}}

###

POST http://localhost:8084/user/login?_format=json HTTP/1.1
Content-Type: application/json
X-CSRF-Token: {{XCSRFToken}}

{
    "name": {{username}},
    "pass": {{password}}
}
###

GET http://localhost:8084/user/1?_format=json HTTP/1.1
Content-Type:: application/json
Cookie: {{Cookie}}


###
GET http://[::1]:8084/api/v1/lesson/1?_format=json
Content-Type:: application/json
Authorization: {{access_token}}


###
GET http://[::1]:8084/api/v1/subject/completed/1/1?_format=json


###
GET http://[::1]:8084/api/v1/lesson/completed/1/1?_format=json



